### ISSUE TITLE
`set-output` commands are deprecated

### ISSUE THREAD

**Issue by ajschmidt8** [rapidsai/shared-action-workflows#11]
Similar to https://github.com/rapidsai/actions/issues/2.

As mentioned in the blog post below, the `set-output` commands are deprecated. It seems the new recommended approach is to use the `$GITHUB_OUTPUT` environment variable. We should update our code accordingly.

**Docs:**
- https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Lines to replace:**
- https://github.com/rapidsai/shared-action-workflows/blob/7700a5c7b6e306e08d2a331545a4956967a2c826/.github/workflows/conda-python-tests.yaml#L72
- https://github.com/rapidsai/shared-action-workflows/blob/7700a5c7b6e306e08d2a331545a4956967a2c826/.github/workflows/conda-cpp-tests.yaml#L72

**Comment by Ethyling** [comment]
Fixed in https://github.com/rapidsai/shared-action-workflows/pull/14
