### ISSUE TITLE
Combine wheels-pure-tests and wheels-manylinux-test

### ISSUE THREAD

**Issue by vyasr** [rapidsai/shared-action-workflows#79]
These two scripts are nearly identical except that the manylinux version uses a matrix job. We should be able to adapt the former to use a matrix with a single entry. One option is to add a new parameter to the manylinux test workflow that controls whether to run the full matrix or not. An alternative that leverages what the workflow already supports is to simply reuse the `matrix_filter` to filter out the unused cases. The latter is the more generic solution and probably preferable, but I raise the possibility of a special filter arg because if we ever have more pure wheels we will end up needing a fairly extensive filter that is replicated across all of them.

**Comment by wence-** [comment]
just FWIW, `matrix_filter` is not the most intuitive thing to use (I, certainly, am not a jq expert)

**Comment by vyasr** [comment]
I'm certainly open to finding a more straightforward approach to supporting filtering. The current solution gets the job done, but I agree that I am also not a skilled `jq` user. @ajschmidt8 knows the most here, if we want to develop an alternate solution would recommend pulling in his help. I think that would be an orthogonal task to the choice of how we resolve this issue though since I'd still be OK leveraging the filter in the shared workflow since it would be mostly set and forget.

**Comment by ajschmidt8** [comment]
Yes, orthogonal. A separate issue can be opened for that.

Feel free to open it and propose alternative solutions @wence-.

**Comment by vyasr** [comment]
Closing, see https://github.com/rapidsai/shared-action-workflows/pull/90#issuecomment-1642525918 for explanation.
