### ISSUE TITLE
Leverage AUDITWHEEL_PLAT in image to simplify auditwheel invocations

### ISSUE THREAD

**Issue by vyasr** [rapidsai/shared-action-workflows#80]
[This conditional logic](https://github.com/rapidsai/shared-action-workflows/blob/branch-23.06/.github/workflows/wheels-manylinux-build.yml#L231) can be replaced with a single call if the platform is specified in the container itself. [auditwheel respects the AUDITWHEEL_PLAT environment variable](https://github.com/pypa/auditwheel/pull/151). Unfortunately it's not documented anywhere else but [cibuildwheel relies on this](https://cibuildwheel.readthedocs.io/en/stable/options/#linux-image) so it should be fairly stable.

Depends on https://github.com/rapidsai/cibuildwheel-imgs/issues/16

**Comment by rlratzel** [comment]
I created [this branch](https://github.com/rapidsai/shared-action-workflows/tree/auditwheel_use_env_var) with the change to be tested.

**Comment by vyasr** [comment]
@rlratzel can you make a test PR to rmm that leverages the new shared-actions-workflows branch?

**Comment by rlratzel** [comment]
> @rlratzel can you make a test PR to rmm that leverages the new shared-actions-workflows branch?

I created [this](https://github.com/rapidsai/rmm/pull/1274) PR. I left it in `Draft` since I'm assuming https://github.com/rapidsai/cibuildwheel-imgs/pull/20 needs to be merged first?

**Comment by leofang** [comment]
btw, if you install the `wheel` package (that offers `bdist_wheel` command; I think one of the packages from PyPA should already depend on it), it has a CLI option for setting the platform name:
```
wheel tags --platform-tag "manylinux2014_x86-64" ./*.whl
```

**Comment by vyasr** [comment]
Thanks @leofang. The goal here isn't just to retag the wheel, we want to run auditwheel and have it generate the properly repaired and tagged wheel for us. This changeset is to make it so that wheels built in a specific container end up with a specific tag so that we don't have to specify it again since the glibc/libstdc++ in the container should fully specify the manylinux tag to be used by any package built and repaired within the container.

**Comment by leofang** [comment]
Yeah I figured you still need to rely on auditwheel (cuQuantum does not). Was offering a solution without it, in case in the future you want to move away from it 🙂

**Comment by vyasr** [comment]
@leofang is there a good reason not to use auditwheel now that it supports library exclusions? Wouldn't you rather have an explicit check of your versioned symbols (and not have to roll that yourself)? It seems somewhat haphazard otherwise since any change to your build environment could accidentally introduce new symbols into your binary.
